---
analytics:
  obligation_refresh_concurrency: 0
  price_feeds:
    - name: TULIP
      price_account: 5RHxy1NbUR15y34uktDbN1a2SWbhgHwkCZ75yK2RJ1FC
      token_decimals: 6
      token_mint: TuLipcqtGVXP9XR62wM8WWCm6a9vhLs7T1uoWBk6FDs
      quote_decimals: -6
  scrape_interval: 30
database:
  analytics_pool_size: 2
  conn_url: ""
  pool_size: 2
debug_log: false
key_path: ""
log_file: ""
programs:
  lending:
    id: ""
    idl_path: ""
  pyth:
    id: ""
    idl_path: ""
rpc_endpoints:
  failover_endpoints: []
  primary_endpoint:
    http_url: ""
    ws_url: ""
telemetry:
  agent_endpoint: ""
  enabled: true
