// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;

use chrono::offset::Utc;
use chrono::DateTime;
#[derive(Queryable, Debug, Identifiable, AsChangeset, Model, Clone)]
#[table_name = "obligations"]
pub struct Obligation {
    pub id: i64,
    pub ltv: f64,
    pub account: String,
    pub scraped_at: DateTime<Utc>,
}

#[derive(Queryable, Debug, Identifiable, AsChangeset, Model, Clone)]
#[table_name = "price_feeds"]
pub struct PriceFeed {
    pub id: i64,
    pub token_mint: String,
    pub price_account: String,
    pub decimals: i16,
    pub price: f64,
    pub scraped_at: DateTime<Utc>,
}
