// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use bonerjams_db::types::DbKey;
use solana_sdk::pubkey::Pubkey;
use chrono::offset::Utc;
use chrono::DateTime;
use serde::{Serialize, Deserialize};
#[derive(Clone, Serialize, Deserialize)]
pub struct Obligation {
    pub ltv: f64,
    pub account: Pubkey,
    pub scraped_at: DateTime<Utc>,
}

#[derive(Clone, Serialize, Deserialize)]
pub struct PriceFeed {
    pub token_mint: Pubkey,
    pub price_account: Pubkey,
    pub decimals: i16,
    pub price: f64,
    pub scraped_at: DateTime<Utc>,
}



impl DbKey for Obligation {
    fn key(&self) -> anyhow::Result<Vec<u8>> {
        Ok(self.account.to_bytes().to_vec())
    }
}

impl DbKey for PriceFeed {
    fn key(&self) -> anyhow::Result<Vec<u8>> {
        Ok(self.price_account.to_bytes().to_vec())
    }
}